// Copyright (c) 2016 The CEF Python authors. All rights reserved.

// The cef_version_win.h and other platform dependent headers
// come from CEF binary distributions. These header files are
// generated by CEF during builds.

#pragma once

#include "base.h"
#include "cef_version_" OS_POSTFIX ".h"

#define CEFPYTHON_VERSION_MAJOR 47
#define CEFPYTHON_VERSION_MINOR 0
#define CEFPYTHON_VERSION \
    STR(CEFPYTHON_VERSION_MAJOR) "." \
    STR(CEFPYTHON_VERSION_MINOR)

// @todo: overwrite during build
// Possible values: "stable", "rc", "alpha"
#define CEFPYTHON_RELEASE_TYPE

// @todo: overwrite during build
#define CEFPYTHON_COMMIT_NUMBER
#define CEFPYTHON_COMMIT_HASH
#define CEFPYTHON_COMMIT_SHORT

#define CHROME_VERSION \
    STR(CHROME_VERSION_MAJOR) "." \
    STR(CHROME_VERSION_MINOR) "." \
    STR(CHROME_VERSION_BUILD) "." \
    STR(CHROME_VERSION_PATCH)
#define CHROMIUM_VERSION CHROME_VERSION
