#!/usr/bin/env python3
"""Post-process the Cython-generated API header for C++ compilation.

Produces two files:
  cefpython_pyXX_fixed.h   - original .h with Windows warning suppression added
  cefpython_api_fixed.h    - stable single-name wrapper included by
                             src/common/cefpython_public_api.h

Called by CMake:
    cmake_fix_header.py <h_in> <fixed_out> <api_wrapper_out> <module_name>
"""
import sys


def main():
    if len(sys.argv) != 5:
        print("Usage: cmake_fix_header.py <h_in> <fixed_out> <api_wrapper_out> <module_name>")
        sys.exit(1)

    h_in, fixed_out, api_wrapper_out, module_name = sys.argv[1:]

    with open(h_in) as f:
        content = f.read()

    pragma = "#pragma warning(disable:4190)"
    if pragma not in content:
        content = pragma + "\n\n" + content

    with open(fixed_out, "w") as f:
        f.write(content)

    with open(api_wrapper_out, "w") as f:
        f.write('/* Generated by cmake_fix_header.py - do not edit */\n')
        f.write('#include "%s_fixed.h"\n' % module_name)

    print("[cmake_fix_header] %s_fixed.h and cefpython_api_fixed.h written" % module_name)


if __name__ == "__main__":
    main()
