#!/usr/bin/env python3
"""Generate Cython .pxi compile-time constant files.

Replaces the compile_time_constants() call in cython_setup.py.
Called by CMake at build time:
    cmake_generate_pxi.py <src_dir>
"""
import os
import platform
import sys


def main():
    if len(sys.argv) < 2:
        print("Usage: cmake_generate_pxi.py <src_dir>")
        sys.exit(1)

    src_dir = sys.argv[1]
    system = platform.system()

    # compile_time_constants.pxi
    with open(os.path.join(src_dir, "compile_time_constants.pxi"), "w", encoding="utf-8") as f:
        f.write("# Generated by cmake_generate_pxi.py - do not edit\n")
        f.write('DEF UNAME_SYSNAME = "%s"\n' % platform.uname()[0])
        f.write("DEF PY_MAJOR_VERSION = %s\n" % sys.version_info.major)
        f.write('cdef extern from "limits.h":\n')
        f.write("    cdef int INT_MIN\n")
        f.write("    cdef int INT_MAX\n")

    # src/platform_cimports.pxi
    with open(os.path.join(src_dir, "platform_cimports.pxi"), "w", encoding="utf-8") as f:
        f.write("# Generated by cmake_generate_pxi.py - do not edit\n")
        f.write("# git update-index --assume-unchanged src/platform_cimports.pxi\n\n")
        if system == "Windows":
            f.write("from windows cimport *\n")
            f.write("from dpi_aware_win cimport *\n")
        elif system == "Darwin":
            f.write("from mac cimport *\n")
        elif system == "Linux":
            f.write("from linux cimport *\n")
            f.write("cimport x11\n")

    # src/extern/cef/platform_cimports.pxi
    cef_dir = os.path.join(src_dir, "extern", "cef")
    with open(os.path.join(cef_dir, "platform_cimports.pxi"), "w", encoding="utf-8") as f:
        f.write("# Generated by cmake_generate_pxi.py - do not edit\n")
        f.write("# git update-index --assume-unchanged src/extern/cef/platform_cimports.pxi\n\n")
        if system == "Windows":
            f.write("from cef_win cimport *\n")
        elif system == "Darwin":
            f.write("from cef_mac cimport *\n")
        elif system == "Linux":
            f.write("from cef_linux cimport *\n")

    print("[cmake_generate_pxi] Generated .pxi files in %s" % src_dir)


if __name__ == "__main__":
    main()
