# This file was generated by setup.py

# Type this command to ignore changes to this file:
#   git update-index --assume-unchanged src/compile_time_constants.pxi

DEF UNAME_SYSNAME = "Windows"
DEF PY_MAJOR_VERSION = 3
