# This file was generated by setup.py

# Type this command to ignore changes to this file:
#   git update-index --assume-unchanged src/platform_cimports.pxi

from windows cimport *
from dpi_aware_win cimport *
